"use client";
import Image from "next/image";
import Link from "next/link";
import { useCallback,useEffect,useRef,useState } from "react";
import { demoImages } from "@/lib/demo-images";
import {homepageService} from"@/services/homepage-service";
import type{HomepageSlide}from"@/types/homepage";

const fallbackSlides:HomepageSlide[]=[
  {id:-1,subtitle:"Güzelliğinize zaman ayırın",title:"Kendiniz için iyi hissettiren bir an yaratın.",description:"Hizmetinizi seçin, uzmanınızı belirleyin ve randevunuzu birkaç dakikada planlayın.",cta_primary_text:"Randevu Al",cta_primary_url:"/appointments/new",cta_secondary_text:"Hizmetleri Keşfet",cta_secondary_url:"/#services",image_url:demoImages.spa,mobile_image_url:null,background_tone:"cream"},
  {id:-2,subtitle:"Evde bakım ritüeli",title:"Bakımınızı evde de devam ettirin.",description:"Özenle seçilmiş bakım ürünlerini keşfedin.",cta_primary_text:"Ürünleri İncele",cta_primary_url:"/products",cta_secondary_text:"Kampanyaları Gör",cta_secondary_url:"/campaigns",image_url:demoImages.products,mobile_image_url:null,background_tone:"nude"},
  {id:-3,subtitle:"Belle Aura ayrıcalıkları",title:"Size özel fırsatlar ve kampanyalar.",description:"Seçili hizmetlerde ve ürünlerde avantajları kaçırmayın.",cta_primary_text:"Kampanyaları Gör",cta_primary_url:"/campaigns",cta_secondary_text:"Alışverişe Başla",cta_secondary_url:"/products",image_url:demoImages.skincare,mobile_image_url:null,background_tone:"peach"},
];
const backgrounds={cream:"bg-[#fffaf4]",nude:"bg-[#f3e5df]",peach:"bg-[#eed8ca]",rose:"bg-[#ead2cf]",beige:"bg-[#e8dfd3]"};

export function HeroSlider(){
  const[slides,setSlides]=useState<HomepageSlide[]|null>(null);const[index,setIndex]=useState(0);const[paused,setPaused]=useState(false);const root=useRef<HTMLElement>(null);
  useEffect(()=>{let active=true;homepageService.slides().then(items=>{if(active){setSlides(items);setIndex(0)}}).catch(()=>{if(active)setSlides(fallbackSlides)});return()=>{active=false}},[]);
  const slideCount=slides?.length??0;
  const move=useCallback((step:number)=>{if(slideCount)setIndex((current)=>(current+step+slideCount)%slideCount)},[slideCount]);
  useEffect(()=>{if(paused||window.matchMedia("(prefers-reduced-motion: reduce)").matches)return;const timer=window.setInterval(()=>move(1),5000);return()=>window.clearInterval(timer);},[move,paused]);
  function keys(event:React.KeyboardEvent){if(event.key==="ArrowLeft")move(-1);if(event.key==="ArrowRight")move(1);}if(!slides?.length)return null;
  return <section ref={root} aria-roledescription="carousel" aria-label="Belle Aura Beauty öne çıkanlar" tabIndex={0} onKeyDown={keys} onMouseEnter={()=>setPaused(true)} onMouseLeave={()=>setPaused(false)} onFocusCapture={()=>setPaused(true)} onBlurCapture={(event)=>{if(!root.current?.contains(event.relatedTarget))setPaused(false);}} className={`relative mx-auto my-6 max-w-[1240px] overflow-hidden rounded-[2rem] transition-colors duration-700 ease-out motion-reduce:transition-none sm:my-8 ${backgrounds[slides[index].background_tone||"cream"]}`}>
    <div className="relative min-h-[510px] sm:min-h-[550px]">{slides.map((slide,position)=><article key={slide.id} aria-hidden={position!==index} className={`absolute inset-0 transition-[opacity,transform] duration-700 ease-out motion-reduce:transform-none motion-reduce:transition-none ${position===index?"z-10 translate-x-0 opacity-100":"pointer-events-none translate-x-4 opacity-0"}`}><div className="grid min-h-[510px] items-center gap-7 px-5 py-8 sm:min-h-[550px] sm:px-10 lg:grid-cols-[.95fr_1.05fr] lg:px-14"><div className="relative z-10 max-w-xl"><p className="text-xs font-bold uppercase tracking-[.24em] text-primary">{slide.subtitle||"Belle Aura Beauty"}</p><h1 className="mt-4 text-4xl leading-[1.04] tracking-[-.035em] sm:text-5xl lg:text-[3.75rem]">{slide.title}</h1><p className="mt-5 max-w-lg text-[15px] leading-7 text-muted sm:text-base">{slide.description}</p><div className="mt-7 flex flex-col gap-3 sm:flex-row">{slide.cta_primary_text&&slide.cta_primary_url?<Link href={slide.cta_primary_url} className="rounded-full bg-primary px-6 py-3 text-center text-sm font-semibold text-primary-foreground hover:bg-[#765246]">{slide.cta_primary_text}</Link>:null}{slide.cta_secondary_text&&slide.cta_secondary_url?<Link href={slide.cta_secondary_url} className="rounded-full border bg-card/50 px-6 py-3 text-center text-sm font-semibold hover:border-primary">{slide.cta_secondary_text}</Link>:null}</div></div><EditorialVisual image={slide.image_url} mobileImage={slide.mobile_image_url} alt={`${slide.title} görseli`} priority={position===0}/></div></article>)}</div>
    <div className="absolute bottom-5 left-1/2 z-20 flex -translate-x-1/2 gap-2.5 rounded-full bg-card/55 px-3 py-2 backdrop-blur-sm" role="tablist" aria-label="Slayt seçimi">{slides.map((slide,position)=><button type="button" role="tab" aria-label={`${position+1}. slayt: ${slide.title}`} aria-selected={position===index} onClick={()=>setIndex(position)} key={slide.title} className={`h-2.5 rounded-full transition-all duration-300 motion-reduce:transition-none ${position===index?"w-9 bg-primary":"w-3 bg-[#c9aa9d] hover:bg-primary/60"}`}/>)}</div>
  </section>;
}

function EditorialVisual({image,mobileImage,alt,priority}:{image:string;mobileImage:string|null;alt:string;priority:boolean}){const external=image.startsWith("http");return <div className="relative mx-auto min-h-[260px] w-full max-w-xl sm:min-h-[410px]"><div className="absolute inset-x-4 inset-y-0 overflow-hidden rounded-[6rem_6rem_1.5rem_1.5rem] bg-muted-surface">{mobileImage?<Image src={mobileImage} alt={alt} fill priority={priority} unoptimized={mobileImage.startsWith("http")} sizes="90vw" className="object-cover sm:hidden"/>:null}<Image src={image} alt={mobileImage?"":alt} fill priority={priority} unoptimized={external} sizes="(max-width: 1024px) 90vw, 48vw" className={`object-cover transition-transform duration-700 hover:scale-[1.03] motion-reduce:transition-none ${mobileImage?"hidden sm:block":""}`}/><div className="absolute inset-0 bg-gradient-to-t from-[#5a3d33]/20 via-transparent to-white/5"/></div><div className="absolute bottom-4 left-0 max-w-48 rounded-2xl bg-card/90 p-4 shadow-sm backdrop-blur"><p className="font-serif text-lg">Belle Aura ritüeli</p><p className="mt-1 text-xs leading-5 text-muted">Sakin, özenli ve size özel.</p></div></div>}
