"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import { appointmentService } from "@/services/appointment-service";
import { ApiError } from "@/types/api";
import type { Appointment, ServiceItem, StaffItem } from "@/types/appointment";
import { Feedback, LoadingState, EmptyState } from "./feedback";
import { money, todayInIstanbul } from "./format";

const stepLabels=["Hizmet","Personel","Tarih","Saat","Onay"];
export function AppointmentWizard(){
  const[step,setStep]=useState(0);const[services,setServices]=useState<ServiceItem[]>([]);const[staff,setStaff]=useState<StaffItem[]>([]);const[slots,setSlots]=useState<string[]>([]);const[service,setService]=useState<ServiceItem|null>(null);const[staffMember,setStaffMember]=useState<StaffItem|null>(null);const[date,setDate]=useState("");const[time,setTime]=useState("");const[note,setNote]=useState("");const[loading,setLoading]=useState(true);const[error,setError]=useState("");const[created,setCreated]=useState<Appointment|null>(null);
  useEffect(()=>{let active=true;appointmentService.services().then((result)=>{if(active)setServices(result.items);}).catch((reason)=>{if(active)setError(reason instanceof ApiError?reason.message:"Hizmetler yüklenemedi.");}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[]);
  function chooseService(item:ServiceItem){setService(item);setStaffMember(null);setDate("");setTime("");setStaff([]);setSlots([]);setError("");}
  function chooseStaff(item:StaffItem){setStaffMember(item);setDate("");setTime("");setSlots([]);setError("");}
  async function next(){setError("");if(step===0){if(!service){setError("Devam etmek için bir hizmet seçin.");return;}setLoading(true);try{const people=await appointmentService.staff(service.id);setStaff(people);setStep(1);}catch(reason){setError(reason instanceof ApiError?reason.message:"Personeller yüklenemedi.");}finally{setLoading(false);}return;}if(step===1){if(!staffMember){setError("Devam etmek için bir personel seçin.");return;}setStep(2);return;}if(step===2){if(!date){setError("Devam etmek için tarih seçin.");return;}setLoading(true);try{const result=await appointmentService.availability(service!.id,staffMember!.id,date);setSlots(result.slots);setTime("");setStep(3);}catch(reason){setError(reason instanceof ApiError?reason.message:"Uygun saatler yüklenemedi.");}finally{setLoading(false);}return;}if(step===3){if(!time){setError("Devam etmek için uygun bir saat seçin.");return;}setStep(4);}}
  async function create(){if(!service||!staffMember||!date||!time)return;setLoading(true);setError("");try{setCreated(await appointmentService.create({service_id:service.id,staff_id:staffMember.id,date,start_time:time,customer_note:note.trim()||undefined}));}catch(reason){setError(reason instanceof ApiError?reason.message:"Randevu oluşturulamadı.");}finally{setLoading(false);}}
  if(created)return <div className="mx-auto max-w-2xl px-4 py-16 sm:px-6"><div className="rounded-card border bg-card p-8 text-center shadow-xl shadow-primary/5"><span className="mx-auto grid size-16 place-items-center rounded-full bg-emerald-500 text-3xl text-white">✓</span><h1 className="mt-6 text-3xl font-bold">Randevunuz oluşturuldu</h1><p className="mt-3 text-muted">Referans numaranız <strong className="text-foreground">{created.reference_no}</strong>. Randevunuzu hesabınızdan takip edebilirsiniz.</p><div className="mt-8 flex flex-col justify-center gap-3 sm:flex-row"><Link href={`/appointments/${created.id}`} className="rounded-xl border px-5 py-3 font-semibold">Randevu detayı</Link><Link href="/appointments" className="rounded-xl bg-primary px-5 py-3 font-semibold text-primary-foreground">Randevularıma git</Link></div></div></div>;
  return <div className="mx-auto max-w-5xl px-4 py-12 sm:px-6 lg:px-8"><div className="mb-10 text-center"><p className="text-xs font-bold uppercase tracking-[.22em] text-primary">Yeni randevu</p><h1 className="mt-3 text-4xl tracking-tight sm:text-5xl">Size uygun zamanı seçin</h1></div><ol className="mb-10 grid grid-cols-5 gap-1 border-b pb-5 sm:gap-3">{stepLabels.map((label,index)=><li key={label} className="min-w-0"><p className={`truncate text-center text-[10px] font-semibold uppercase tracking-wide sm:text-xs ${index===step?"text-primary":"text-muted"}`}><span className="mr-1 font-serif">0{index+1}</span>{label}</p></li>)}</ol><section className="rounded-[2rem] bg-card p-5 sm:p-9">{error?<div className="mb-5"><Feedback>{error}</Feedback></div>:null}{loading?<LoadingState/>:<>
    {step===0?<div><h2 className="text-xl font-bold">Hizmet seçin</h2><p className="mt-1 text-sm text-muted">Randevu almak istediğiniz hizmeti belirleyin.</p>{services.length?<div className="mt-6 grid gap-4 md:grid-cols-2">{services.map((item)=><button type="button" key={item.id} onClick={()=>chooseService(item)} className={`rounded-xl border p-5 text-left transition ${service?.id===item.id?"border-primary bg-primary/5 ring-2 ring-primary/15":"hover:border-primary/40"}`}><div className="flex justify-between gap-4"><h3 className="font-bold">{item.name}</h3><span className="font-semibold text-primary">{money(item.price)}</span></div><p className="mt-2 line-clamp-2 text-sm text-muted">{item.description||"Bu hizmet için açıklama bulunmuyor."}</p><p className="mt-4 text-xs font-semibold text-muted">{item.duration_minutes} dakika</p></button>)}</div>:<div className="mt-6"><EmptyState title="Aktif hizmet bulunamadı" description="Şu anda randevuya açık bir hizmet bulunmuyor."/></div>}</div>:null}
    {step===1?<div><h2 className="text-xl font-bold">Personel seçin</h2><p className="mt-1 text-sm text-muted">{service?.name} hizmetini veren uygun personeller.</p>{staff.length?<div className="mt-6 grid gap-4 md:grid-cols-2">{staff.map((item)=><button type="button" key={item.id} onClick={()=>chooseStaff(item)} className={`flex gap-4 rounded-xl border p-5 text-left transition ${staffMember?.id===item.id?"border-primary bg-primary/5 ring-2 ring-primary/15":"hover:border-primary/40"}`}><span className="grid size-12 shrink-0 place-items-center rounded-full bg-secondary text-lg font-bold text-secondary-foreground">{item.name.charAt(0)}</span><span><strong className="block">{item.name}</strong><span className="mt-1 block text-sm text-muted">{item.bio||"Randevu için uygun uzman personel"}</span><span className="mt-2 block text-xs font-semibold text-primary">{item.service_name} · {item.duration_minutes} dk</span></span></button>)}</div>:<div className="mt-6"><EmptyState title="Uygun personel bulunamadı" description="Bu hizmeti veren aktif ve randevuya açık personel bulunmuyor."/></div>}</div>:null}
    {step===2?<div><h2 className="text-xl font-bold">Tarih seçin</h2><p className="mt-1 text-sm text-muted">Geçmiş tarihler seçilemez.</p><label className="mt-7 grid max-w-sm gap-2 text-sm font-semibold">Randevu tarihi<input type="date" min={todayInIstanbul()} value={date} onChange={(event)=>{setDate(event.target.value);setTime("");}} className="h-12 rounded-xl border bg-card px-4 outline-none focus:border-primary focus:ring-3 focus:ring-primary/10"/></label></div>:null}
    {step===3?<div><h2 className="text-xl font-bold">Uygun saat seçin</h2><p className="mt-1 text-sm text-muted">Saatler backend’in güncel uygunluk hesabından gelir.</p>{slots.length?<div className="mt-6 grid grid-cols-3 gap-3 sm:grid-cols-5 md:grid-cols-7">{slots.map((slot)=><button type="button" key={slot} onClick={()=>setTime(slot)} className={`rounded-xl border px-3 py-3 text-sm font-semibold transition ${time===slot?"border-primary bg-primary text-primary-foreground":"hover:border-primary"}`}>{slot}</button>)}</div>:<div className="mt-6"><EmptyState title="Uygun saat yok" description="Seçilen tarihte uygun saat bulunamadı. Önceki adıma dönüp başka bir tarih deneyin."/></div>}</div>:null}
    {step===4?<div><h2 className="text-xl font-bold">Randevunuzu kontrol edin</h2><div className="mt-6 grid gap-3 rounded-xl bg-muted-surface p-5 text-sm"><Summary label="Hizmet" value={service!.name}/><Summary label="Personel" value={staffMember!.name}/><Summary label="Tarih" value={new Intl.DateTimeFormat("tr-TR",{dateStyle:"long"}).format(new Date(`${date}T12:00:00`))}/><Summary label="Saat" value={time}/><Summary label="Süre" value={`${service!.duration_minutes} dakika`}/><Summary label="Fiyat" value={money(service!.price)}/></div><label className="mt-6 grid gap-2 text-sm font-semibold">Müşteri notu <span className="font-normal text-muted">(isteğe bağlı)</span><textarea value={note} onChange={(event)=>setNote(event.target.value)} maxLength={2000} rows={4} className="rounded-xl border bg-card p-3.5 outline-none focus:border-primary focus:ring-3 focus:ring-primary/10" placeholder="Randevunuzla ilgili paylaşmak istediğiniz bilgi…"/><span className="text-right text-xs font-normal text-muted">{note.length}/2000</span></label></div>:null}
  </>}</section><div className="mt-5 flex items-center justify-between gap-3"><Button variant="ghost" onClick={()=>{setError("");setStep(Math.max(0,step-1));}} disabled={step===0||loading}>← Geri</Button>{step<4?<Button onClick={next} disabled={loading||(step===0&&!service)||(step===1&&!staffMember)||(step===2&&!date)||(step===3&&!time)}>Devam →</Button>:<Button onClick={create} disabled={loading}>Randevuyu oluştur</Button>}</div></div>;
}
function Summary({label,value}:{label:string;value:string}){return <div className="flex justify-between gap-4"><span className="text-muted">{label}</span><strong className="text-right">{value}</strong></div>;}
