"use client";
/* eslint-disable @next/next/no-img-element */
import Link from "next/link";
import Image from "next/image";
import { useEffect, useState } from "react";
import { appointmentService } from "@/services/appointment-service";
import { commerceService, mediaUrl } from "@/services/commerce-service";
import type { ServiceItem, StaffItem } from "@/types/appointment";
import type { Category, Product, PublicCoupon } from "@/types/commerce";
import { money } from "@/features/appointments/format";
import { ProductCard } from "./product-card";
import { demoImages } from "@/lib/demo-images";
import { Reveal } from "@/components/ui/reveal";
import {homepageService} from"@/services/homepage-service";
import type{HomepageBanner}from"@/types/homepage";

const expertFallback = [
  { id: -1, name: "Lotus Uzmanı", service_name: "Cilt Bakımı", bio: "Cildinizin ihtiyacına göre özenle şekillenen kişisel bakım ritüelleri.", avatar_path: null },
  { id: -2, name: "Lotus Uzmanı", service_name: "Saç Bakımı", bio: "Saçınıza canlılık kazandıran profesyonel dokunuşlar ve bakım önerileri.", avatar_path: null },
  { id: -3, name: "Lotus Uzmanı", service_name: "Güzellik Ritüelleri", bio: "Kendinizi iyi hissettiren sakin, dengeli ve size özel bir deneyim.", avatar_path: null },
] as StaffItem[];

export function HomeShowcase() {
  const [services, setServices] = useState<ServiceItem[]>([]); const [products, setProducts] = useState<Product[]>([]); const [categories, setCategories] = useState<Category[]>([]); const [experts, setExperts] = useState<StaffItem[]>(expertFallback);const[banners,setBanners]=useState<HomepageBanner[]>([]);const[coupons,setCoupons]=useState<PublicCoupon[]>([]); useEffect(() => { let active = true; Promise.all([appointmentService.services(), commerceService.products({ per_page: 4, sort: "newest", in_stock: true }), commerceService.categories()]).then(async ([servicePage, productPage, nextCategories]) => { if (!active) return; const featured = servicePage.items.slice(0, 3); setServices(featured); setProducts(productPage.items.slice(0, 4)); setCategories(nextCategories.slice(0, 3)); const groups = await Promise.allSettled(featured.map((service) => appointmentService.staff(service.id))); if (!active) return; const unique = new Map<number, StaffItem>(); for (const group of groups) if (group.status === "fulfilled") for (const staff of group.value) if (!unique.has(staff.id)) unique.set(staff.id, staff); const found = [...unique.values()].slice(0, 3); if (found.length) setExperts([...found, ...expertFallback].slice(0, 3)); }).catch(() => { });homepageService.banners().then(x=>{if(active)setBanners(x)}).catch(()=>{});homepageService.coupons().then(x=>{if(active)setCoupons(x)}).catch(()=>{}); return () => { active = false; }; }, []); return <>
    <HomeBanners banners={banners.filter(x=>x.position==="home_top")}/>
    <section id="services" className="bg-card"><div className="mx-auto max-w-7xl px-4 py-14 sm:px-6 sm:py-16 lg:px-8 lg:py-20"><Title eyebrow="Bakım ritüelleri" title="Size Özel Hizmetler" text="Kendinizi iyi hissettirecek profesyonel dokunuşları keşfedin." /><div className="mt-9 grid gap-7 md:grid-cols-3">{services.map((item, index) => <ServiceCard key={item.id} item={item} index={index} />)}</div><More href="/services">Tüm Hizmetleri Gör</More></div></section>
    <HomeBanners banners={banners.filter(x=>x.position==="home_after_services")}/>
    <HomeBanners banners={banners.filter(x=>x.position==="campaign")}/>
    <section className="mx-auto max-w-7xl px-4 py-14 sm:px-6 sm:py-16 lg:px-8 lg:py-20"><Title eyebrow="Evde bakım" title="Bakımınızı Evde Devam Ettirin" text="Profesyonel bakım hissini günlük rutininize taşıyan seçkimiz." /><div className="mt-8 grid gap-x-5 gap-y-8 sm:grid-cols-2 lg:grid-cols-4">{products.map(item => <ProductCard key={item.id} product={item} />)}</div><More href="/products">Tüm Ürünleri Gör</More></section>
    <HomeBanners banners={banners.filter(x=>x.position==="home_after_products")}/>
    <CouponSection coupons={coupons}/>
    <section className="bg-muted-surface"><div className="mx-auto max-w-7xl px-4 py-14 sm:px-6 sm:py-16 lg:px-8 lg:py-20"><Title eyebrow="Koleksiyonlar" title="Kategorileri Keşfet" text="Günlük ritüelinize uygun ürünleri seçilmiş kategorilerde keşfedin." /><div className="mt-8 grid gap-5 md:grid-cols-3">{categories.map((item, index) => <Link key={item.id} href={`/products?category=${encodeURIComponent(item.slug)}`} className={`group relative min-h-60 overflow-hidden rounded-[1.5rem] p-6 ${["bg-[#e6c8ba]", "bg-[#d9d2c5]", "bg-[#eddbd0]"][index % 3]}`}><div className="absolute -bottom-16 -right-10 size-48 rounded-full border border-white/50 bg-white/20 transition-transform duration-300 group-hover:scale-110 motion-reduce:transition-none" /><p className="text-xs font-bold uppercase tracking-widest text-muted">Koleksiyon 0{index + 1}</p><h3 className="mt-3 max-w-52 text-3xl">{item.name}</h3><p className="mt-3 max-w-52 text-sm leading-6 text-muted">{item.description || "Bakım rutininizi tamamlayan özenli seçki."}</p><span className="absolute bottom-6 left-6 text-sm font-semibold">Ürünleri Gör →</span></Link>)}</div></div></section>
    <section className="mx-auto max-w-7xl px-4 py-14 sm:px-6 sm:py-16 lg:px-8 lg:py-20"><Title eyebrow="Lotus ekibi" title="Uzmanlarımızla Tanışın" text="Deneyimi, özeni ve kişisel yaklaşımı bir araya getiren uzmanlarımız." /><div className="mt-9 grid gap-7 md:grid-cols-3">{experts.map((expert, index) => <ExpertCard key={`${expert.id}-${index}`} expert={expert} index={index} />)}</div></section>
    <section className="bg-[#f4ede6]"><div className="mx-auto max-w-7xl px-4 py-20 sm:px-6 lg:px-8 lg:py-28"><Title eyebrow="Kolay planlama" title="Randevunuzu 4 Adımda Oluşturun" text="Size uygun bakım deneyimini birkaç dakika içinde planlayın." /><div className="mt-12 grid gap-8 sm:grid-cols-2 lg:grid-cols-4">{[["01", "Hizmetini seç", "İhtiyacınıza uygun bakımı keşfedin."], ["02", "Uzmanını seç", "Size eşlik edecek uzmanı belirleyin."], ["03", "Tarih ve saati belirle", "Takviminize uyan zamanı seçin."], ["04", "Randevunu onayla", "Bilgilerinizi kontrol edip tamamlayın."]].map(([no, title, text]) => <article key={no} className="border-t border-primary/30 pt-6"><span className="font-serif text-5xl text-primary/60">{no}</span><h3 className="mt-6 text-2xl">{title}</h3><p className="mt-3 text-sm leading-6 text-muted">{text}</p></article>)}</div><div className="mt-12 text-center"><Link href="/appointments/new" className="inline-flex rounded-full bg-primary px-8 py-3.5 text-sm font-semibold text-primary-foreground">Randevu Al</Link></div></div></section>
  </>
}

const bannerTones:Record<string,string>={cream:"bg-[#fffaf4]",nude:"bg-[#f3e5df]",peach:"bg-[#eed8ca]",rose:"bg-[#ead2cf]",beige:"bg-[#e8dfd3]"};
function HomeBanners({banners}:{banners:HomepageBanner[]}){if(!banners.length)return null;return <>{banners.map(banner=><section key={banner.id} className="mx-auto w-full max-w-[1160px] overflow-hidden px-4 py-6 sm:px-6"><Reveal><div className={`grid overflow-hidden rounded-[1.5rem] md:min-h-[280px] md:grid-cols-[1.08fr_.92fr] ${bannerTones[banner.background_tone||"peach"]}`}><div className="flex min-w-0 flex-col justify-center px-6 py-8 sm:px-9 md:py-9 lg:px-11"><p className="text-xs font-bold uppercase tracking-[.22em] text-primary">{banner.subtitle||"Lotus ayrıcalığı"}</p><h2 className="mt-3 text-3xl leading-tight text-[#5f4035] sm:text-4xl lg:text-[2.5rem]">{banner.title}</h2>{banner.description?<p className="mt-4 max-w-lg text-sm leading-6 text-muted sm:text-[15px] sm:leading-7">{banner.description}</p>:null}{banner.cta_text&&banner.cta_url?<Link href={banner.cta_url} className="mt-5 w-fit rounded-full bg-primary px-6 py-3 text-sm font-semibold text-primary-foreground">{banner.cta_text}</Link>:null}</div>{banner.image_url?<div className="relative min-h-48 overflow-hidden md:min-h-[280px]"><Image src={banner.image_url} alt={`${banner.title} banner görseli`} fill unoptimized={banner.image_url.startsWith("http")} sizes="(max-width: 767px) 100vw, 46vw" className="object-cover"/></div>:<div className="relative min-h-48 overflow-hidden bg-white/15 md:min-h-[280px]" aria-hidden="true"><div className="absolute -bottom-24 left-[15%] size-[78%] rounded-full border border-white/40 bg-white/20"/><div className="absolute right-[18%] top-[18%] h-[64%] w-32 rounded-[4rem] bg-card/35"/></div>}</div></Reveal></section>)}</>}

function CouponSection({coupons}:{coupons:PublicCoupon[]}){if(!coupons.length)return null;return <section className="bg-[#f4ede6]"><div className="mx-auto max-w-7xl px-4 py-12 sm:px-6 lg:px-8"><Title eyebrow="Lotus ayrıcalıkları" title="Size Özel Kuponlar" text="Aktif fırsatlardan yararlanmak için kupon kodunu checkout adımında kullanın."/><div className="mt-7 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{coupons.map(coupon=><CouponCard key={coupon.id} coupon={coupon}/>)}</div></div></section>}
function CouponCard({coupon}:{coupon:PublicCoupon}){const[copied,setCopied]=useState(false);async function copy(){try{await navigator.clipboard.writeText(coupon.code);setCopied(true);window.setTimeout(()=>setCopied(false),2400)}catch{setCopied(false)}}const discount=coupon.type==="percentage"?`%${Number(coupon.value)}`:`₺${Number(coupon.value).toLocaleString("tr-TR")}`;const expires=coupon.expires_at?new Intl.DateTimeFormat("tr-TR",{day:"2-digit",month:"long",year:"numeric"}).format(new Date(coupon.expires_at.replace(" ","T"))):"Süresiz";return <Reveal><article className="flex h-full min-w-0 flex-col rounded-[1.5rem] border border-primary/15 bg-card p-5 shadow-[0_12px_32px_rgba(95,64,53,.05)]"><div className="flex items-start justify-between gap-4"><code className="rounded-lg bg-secondary px-3 py-2 text-sm font-bold tracking-[.12em] text-primary">{coupon.code}</code><strong className="font-serif text-3xl text-primary">{discount}</strong></div>{coupon.minimum_order_amount?<p className="mt-4 text-sm text-muted">Minimum sepet: <strong className="text-foreground">₺{Number(coupon.minimum_order_amount).toLocaleString("tr-TR")}</strong></p>:null}<p className="mt-2 text-xs text-muted">Son kullanım: {expires}</p><button type="button" onClick={copy} className="mt-5 rounded-full border border-primary/25 px-5 py-2.5 text-sm font-semibold text-primary hover:bg-secondary">Kodu Kopyala</button><p className={`mt-2 min-h-5 text-center text-xs font-semibold text-primary transition-opacity ${copied?"opacity-100":"opacity-0"}`} aria-live="polite">Kupon kodu kopyalandı</p></article></Reveal>}

function ServiceCard({ item, index }: { item: ServiceItem; index: number }) { return <Reveal delay={index * 80}><article className="group transition-transform duration-300 hover:-translate-y-1"><div className="relative aspect-[5/6] overflow-hidden rounded-[5rem_5rem_1.25rem_1.25rem]"><Image src={[demoImages.skincare, demoImages.hair, demoImages.spa][index % 3]} alt={`${item.name} hizmetini temsil eden beauty fotoğrafı`} fill sizes="(max-width: 768px) 100vw, 33vw" className="object-cover transition-transform duration-300 group-hover:scale-[1.04] motion-reduce:transition-none" /><div className="absolute inset-0 bg-gradient-to-t from-[#4c3229]/35 via-transparent to-transparent" /><span className="absolute bottom-4 left-4 font-serif text-4xl text-white/75">0{index + 1}</span></div><p className="mt-5 text-xs font-bold uppercase tracking-[.18em] text-muted">{item.duration_minutes} dakika · {money(item.price)}</p><h3 className="mt-2 text-[1.7rem]">{item.name}</h3><p className="mt-2 line-clamp-2 text-sm leading-6 text-muted">{item.description || "Size özel, özenli ve dingin bir bakım deneyimi."}</p><Link href="/appointments/new" className="mt-4 inline-flex border-b border-primary pb-1 text-sm font-semibold text-primary">Randevu Al →</Link></article></Reveal> }
function ExpertCard({ expert, index }: { expert: StaffItem; index: number }) { const image = mediaUrl(expert.avatar_path); return <article className="text-center"><div className={`mx-auto grid aspect-[4/5] max-w-sm place-items-center overflow-hidden rounded-[8rem_8rem_2rem_2rem] ${["bg-[#e5c4bd]", "bg-[#ddd6c9]", "bg-[#ead2c5]"][index % 3]}`}>{image ? <img src={image} alt={`${expert.name} portresi`} className="size-full object-cover" /> : <span className="grid size-28 place-items-center rounded-full bg-card/50 font-serif text-5xl text-primary/60" aria-hidden="true">{expert.name.charAt(0)}</span>}</div><p className="mt-6 text-xs font-bold uppercase tracking-[.18em] text-primary">{expert.service_name}</p><h3 className="mt-2 text-3xl">{expert.name}</h3><p className="mx-auto mt-3 max-w-sm text-sm leading-6 text-muted">{expert.bio || "Size özel bakım deneyimini özenle planlayan Lotus uzmanı."}</p><Link href="/appointments/new" className="mt-5 inline-flex border-b border-primary pb-1 text-sm font-semibold">Randevu Al →</Link></article> }
function Title({ eyebrow, title, text }: { eyebrow: string; title: string; text: string }) { return <div><p className="text-xs font-bold uppercase tracking-[.22em] text-primary">{eyebrow}</p><h2 className="mt-3 text-4xl lg:text-[2.75rem]">{title}</h2><p className="mt-3 max-w-xl text-sm leading-6 text-muted">{text}</p></div> }
function More({ href, children }: { href: string; children: React.ReactNode }) { return <div className="mt-9 text-center"><Link href={href} className="inline-flex border-b border-primary pb-1 text-sm font-semibold text-primary">{children} →</Link></div> }
