"use client";

import { FormEvent, useEffect, useState } from "react";
import { Button } from "@/components/ui/button";
import { commerceService } from "@/services/commerce-service";
import { ApiError } from "@/types/api";
import type { Category, Product, ProductFilters } from "@/types/commerce";
import type { PaginationMeta } from "@/types/appointment";
import { EmptyState, Feedback, LoadingState } from "@/features/appointments/feedback";
import { ProductCard } from "./product-card";

const initial:ProductFilters={search:"",category:"",min_price:"",max_price:"",in_stock:undefined,sort:"newest",page:1,per_page:12};
export function ProductBrowser({initialFilters={}}:{initialFilters?:ProductFilters}){const starting={...initial,...initialFilters};const[draft,setDraft]=useState(starting);const[filters,setFilters]=useState(starting);const[products,setProducts]=useState<Product[]>([]);const[categories,setCategories]=useState<Category[]>([]);const[meta,setMeta]=useState<PaginationMeta|null>(null);const[loading,setLoading]=useState(true);const[error,setError]=useState("");
  useEffect(()=>{let active=true;commerceService.categories().then((data)=>{if(active)setCategories(data);}).catch(()=>{});return()=>{active=false;};},[]);
  useEffect(()=>{let active=true;const params=new URLSearchParams();for(const[key,value]of Object.entries(filters))if(value!==undefined&&value!=="")params.set(key,String(value));window.history.replaceState(null,"",`${window.location.pathname}?${params.toString()}`);commerceService.products(filters).then((result)=>{if(active){setProducts(result.items);setMeta(result.meta);}}).catch((reason)=>{if(active)setError(reason instanceof ApiError?reason.message:"Ürünler yüklenemedi.");}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[filters]);
  function apply(event:FormEvent){event.preventDefault();setLoading(true);setError("");setFilters({...draft,page:1});}
  function reset(){setDraft(initial);setLoading(true);setError("");setFilters(initial);}
  function page(value:number){setLoading(true);setError("");setFilters((current)=>({...current,page:value}));window.scrollTo({top:0,behavior:"smooth"});}
  function sort(value:string){setDraft((current)=>({...current,sort:value,page:1}));setFilters((current)=>({...current,sort:value,page:1}));setLoading(true);}
  const controls=<FilterControls draft={draft} categories={categories} setDraft={setDraft} reset={reset}/>;
  return <div className="mx-auto max-w-7xl px-4 py-12 sm:px-6 lg:px-8"><header className="py-8 sm:py-12"><p className="text-xs font-bold uppercase tracking-[.22em] text-primary">Online mağaza</p><h1 className="mt-3 text-5xl tracking-tight sm:text-7xl">Ürünler</h1><p className="mt-5 max-w-2xl leading-7 text-muted">Profesyonel bakım ürünlerini keşfedin; kategori, fiyat ve stok durumuna göre kolayca filtreleyin.</p></header>
    <details className="mt-6 rounded-card border bg-card p-4 lg:hidden"><summary className="cursor-pointer list-none font-semibold">Filtreleri Göster <span className="float-right">⌄</span></summary><form onSubmit={apply} className="mt-5 grid gap-5 border-t pt-5">{controls}<Button type="submit">Filtreleri Uygula</Button></form></details>
    <div className="mt-8 grid gap-8 lg:grid-cols-[270px_1fr]"><aside className="hidden lg:block"><form onSubmit={apply} className="sticky top-24 grid gap-6 rounded-card border bg-card p-5 shadow-sm"><div><h2 className="text-lg font-bold">Filtreler</h2><p className="mt-1 text-xs text-muted">Sonuçları daraltın</p></div>{controls}<Button type="submit">Filtreleri Uygula</Button></form></aside><main className="min-w-0"><div className="mb-5 flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><p className="text-sm text-muted"><strong className="text-foreground">{meta?.total??0}</strong> ürün bulundu</p><label className="flex items-center gap-3 text-sm text-muted">Sırala<select value={draft.sort} onChange={(event)=>sort(event.target.value)} className="h-10 rounded-xl border bg-card px-3 font-medium text-foreground"><option value="newest">En yeni</option><option value="oldest">En eski</option><option value="price_asc">Fiyat: Artan</option><option value="price_desc">Fiyat: Azalan</option><option value="name_asc">Ada göre</option></select></label></div>{error?<Feedback>{error}</Feedback>:loading?<LoadingState label="Ürünler yükleniyor…"/>:products.length?<div className="grid gap-5 sm:grid-cols-2 xl:grid-cols-3">{products.map((product)=><ProductCard key={product.id} product={product}/>)}</div>:<EmptyState title="Aradığınız ürün bulunamadı" description="Filtreleri temizleyerek veya arama kelimenizi değiştirerek tekrar deneyin." action={<Button onClick={reset}>Filtreleri Temizle</Button>}/>} {meta&&meta.last_page>1?<nav aria-label="Ürün sayfaları" className="mt-10 flex items-center justify-center gap-3"><Button variant="ghost" onClick={()=>page(Math.max(1,meta.page-1))} disabled={loading||meta.page<=1}>← Önceki</Button><span className="rounded-xl border bg-card px-4 py-2 text-sm font-semibold">{meta.page} / {meta.last_page}</span><Button variant="ghost" onClick={()=>page(Math.min(meta.last_page,meta.page+1))} disabled={loading||meta.page>=meta.last_page}>Sonraki →</Button></nav>:null}</main></div></div>;
}

function FilterControls({draft,categories,setDraft,reset}:{draft:ProductFilters;categories:Category[];setDraft:React.Dispatch<React.SetStateAction<ProductFilters>>;reset:()=>void}){return <><label className="grid gap-2 text-sm font-semibold">Ürün ara<input value={draft.search??""} onChange={(event)=>setDraft({...draft,search:event.target.value})} placeholder="İsim, SKU veya açıklama" className="h-11 rounded-xl border bg-card px-3 outline-none focus:border-primary focus:ring-3 focus:ring-primary/10"/></label><fieldset><legend className="text-sm font-semibold">Kategori</legend><div className="mt-2 grid gap-1"><button type="button" onClick={()=>setDraft({...draft,category:""})} className={`rounded-lg px-3 py-2 text-left text-sm ${!draft.category?"bg-primary text-primary-foreground":"hover:bg-muted-surface"}`}>Tüm kategoriler</button>{categories.map((item)=><button type="button" key={item.id} onClick={()=>setDraft({...draft,category:item.slug})} className={`rounded-lg px-3 py-2 text-left text-sm ${draft.category===item.slug?"bg-primary text-primary-foreground":"hover:bg-muted-surface"}`}>{item.name}</button>)}</div></fieldset><fieldset><legend className="text-sm font-semibold">Fiyat aralığı</legend><div className="mt-2 grid grid-cols-2 gap-2"><input aria-label="Minimum fiyat" type="number" min="0" step="0.01" value={draft.min_price??""} onChange={(event)=>setDraft({...draft,min_price:event.target.value})} placeholder="Min" className="h-11 min-w-0 rounded-xl border bg-card px-3"/><input aria-label="Maksimum fiyat" type="number" min="0" step="0.01" value={draft.max_price??""} onChange={(event)=>setDraft({...draft,max_price:event.target.value})} placeholder="Maks" className="h-11 min-w-0 rounded-xl border bg-card px-3"/></div></fieldset><label className="flex items-center gap-3 rounded-xl bg-muted-surface p-3 text-sm font-semibold"><input type="checkbox" checked={draft.in_stock===true} onChange={(event)=>setDraft({...draft,in_stock:event.target.checked?true:undefined})} className="size-4 accent-primary"/> Yalnız stokta olanlar</label><button type="button" onClick={reset} className="text-left text-sm font-semibold text-muted hover:text-primary">Filtreleri temizle</button></>}
