"use client";
/* eslint-disable @next/next/no-img-element */

import Link from "next/link";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { Button } from "@/components/ui/button";
import { useAuth } from "@/hooks/use-auth";
import { commerceService,mediaUrl } from "@/services/commerce-service";
import { ApiError } from "@/types/api";
import type { Product } from "@/types/commerce";
import { Feedback,LoadingState } from "@/features/appointments/feedback";
import { CommerceBadge } from "./badge";
import { commerceMoney } from "./commerce-format";

export function ProductDetail({slug}:{slug:string}){const[product,setProduct]=useState<Product|null>(null);const[quantity,setQuantity]=useState(1);const[loading,setLoading]=useState(true);const[adding,setAdding]=useState(false);const[error,setError]=useState("");const[message,setMessage]=useState("");const{user}=useAuth();const router=useRouter();useEffect(()=>{let active=true;commerceService.product(slug).then((data)=>{if(active)setProduct(data);}).catch((reason)=>{if(active)setError(reason instanceof ApiError?reason.message:"Ürün yüklenemedi.");}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[slug]);
  async function add(){if(!product)return;if(!user){router.push(`/login?next=${encodeURIComponent(`/products/${slug}`)}`);return;}if(user.role_slug!=="customer"){setError("Sepet yalnız müşteri hesapları tarafından kullanılabilir.");return;}setAdding(true);setError("");try{await commerceService.addCart(product.id,quantity);setMessage("Ürün sepetinize eklendi.");}catch(cause){setError(cause instanceof ApiError?cause.message:"Ürün sepete eklenemedi.");}finally{setAdding(false);}}
  if(loading)return <div className="mx-auto max-w-6xl px-4 py-10"><LoadingState label="Ürün yükleniyor…"/></div>;if(!product)return <div className="mx-auto max-w-6xl px-4 py-10"><Feedback>{error||"Ürün bulunamadı."}</Feedback></div>;const stock=!product.track_stock||product.stock_quantity>0;const image=mediaUrl(product.image?.path??product.image_path);const max=product.track_stock?Math.max(1,product.stock_quantity):99;
  return <div className="mx-auto max-w-6xl px-4 py-10 sm:px-6 lg:px-8"><Link href="/products" className="text-sm font-semibold text-primary">← Ürünlere dön</Link><div className="mt-6 grid gap-8 lg:grid-cols-2"><div className="grid aspect-square place-items-center overflow-hidden rounded-card bg-muted-surface">{image?<img src={image} alt={product.name} className="size-full object-cover"/>:<span className="text-7xl text-muted">◇</span>}</div><div className="py-2"><div className="flex items-center gap-3"><span className="text-sm font-semibold text-muted">{product.category_name||"Kategorisiz"}</span><CommerceBadge tone={stock?"success":"danger"}>{stock?"Stokta":"Stokta yok"}</CommerceBadge></div><h1 className="mt-4 text-4xl font-bold tracking-tight">{product.name}</h1>{product.short_description?<p className="mt-4 text-lg text-muted">{product.short_description}</p>:null}<div className="mt-6 flex items-baseline gap-3">{product.sale_price?<><strong className="text-3xl text-primary">{commerceMoney(product.sale_price)}</strong><span className="text-lg text-muted line-through">{commerceMoney(product.price)}</span></>:<strong className="text-3xl text-primary">{commerceMoney(product.price)}</strong>}</div>{error?<div className="mt-5"><Feedback>{error}</Feedback></div>:null}{message?<div className="mt-5"><Feedback type="success">{message} <Link href="/cart" className="font-bold underline">Sepete git</Link></Feedback></div>:null}<div className="mt-7 flex items-center gap-3"><div className="flex h-11 items-center rounded-xl border"><button type="button" className="size-11 text-lg" onClick={()=>setQuantity((value)=>Math.max(1,value-1))} disabled={!stock}>−</button><span className="w-10 text-center font-semibold">{quantity}</span><button type="button" className="size-11 text-lg" onClick={()=>setQuantity((value)=>Math.min(max,value+1))} disabled={!stock}>+</button></div><Button onClick={add} disabled={!stock||adding} className="flex-1">{adding?"Ekleniyor…":stock?"Sepete ekle":"Ürün tükendi"}</Button></div>{product.track_stock&&stock?<p className="mt-2 text-xs text-muted">Stokta {product.stock_quantity} adet</p>:null}<div className="mt-9 border-t pt-7"><h2 className="text-lg font-bold">Ürün açıklaması</h2><p className="mt-3 whitespace-pre-line leading-7 text-muted">{product.description||"Bu ürün için detaylı açıklama bulunmuyor."}</p></div></div></div></div>;
}
