"use client";

import Link from "next/link";
import { useEffect, useRef, useState } from "react";
import { usePathname, useRouter } from "next/navigation";
import { useAuth } from "@/hooks/use-auth";
import { commerceService } from "@/services/commerce-service";
import type { Cart } from "@/types/commerce";
import { appointmentService } from "@/services/appointment-service";
import type { ServiceItem } from "@/types/appointment";
import { categoryFor, serviceCategories, serviceCategorySlugs, type ServiceCategory } from "@/features/services/service-ui";

const navigation = [["Ana Sayfa","/"],["Hakkımızda","/about"],["Hizmetler","/services"],["Paketler","/packages"],["Ürünler","/products"],["Kampanyalar","/campaigns"],["Blog","/blog"],["İletişim","/contact"]] as const;

export function SiteNavbar(){
  const [open,setOpen]=useState(false);const [cartCount,setCartCount]=useState(0);const [services,setServices]=useState<ServiceItem[]>([]);const {user,hydrated,logout}=useAuth();const router=useRouter();const pathname=usePathname();
  useEffect(()=>{let active=true;appointmentService.services().then((page)=>{if(active)setServices(page.items);}).catch(()=>{});return()=>{active=false;};},[]);
  useEffect(()=>{if(user?.role_slug!=="customer")return;let active=true;const update=(cart:Cart)=>{if(active)setCartCount(cart.items.reduce((sum,item)=>sum+item.quantity,0));};commerceService.cart().then(update).catch(()=>{});const listener=(event:Event)=>update((event as CustomEvent<Cart>).detail);window.addEventListener("cart:updated",listener);return()=>{active=false;window.removeEventListener("cart:updated",listener);};},[user]);
  async function signOut(){await logout();setCartCount(0);setOpen(false);router.replace("/");router.refresh();}
  const panel=user?.role_slug==="admin"||user?.role_slug==="super_admin"?{href:"/admin",label:"Admin Panel"}:user?.role_slug==="staff"?{href:"/staff",label:"Personel Paneli"}:null;
  return <header className="sticky top-0 z-40 border-b bg-card/90 backdrop-blur-xl"><TopContactBar/><nav className="mx-auto flex min-h-24 max-w-[1440px] flex-wrap items-center justify-between gap-4 px-5 sm:px-8 lg:px-10 xl:px-12">
    <Link href="/" className="flex shrink-0 items-center gap-3" onClick={()=>setOpen(false)}><span className="grid size-11 place-items-center rounded-full border border-primary font-serif text-xl text-primary">L</span><span className="font-serif text-[1.35rem]">Belle Aura Beauty</span></Link>
    <div className="hidden items-center gap-1 lg:flex xl:gap-2">{navigation.map(([label,href])=>{const active=isActivePath(pathname,href);return label==="Hizmetler"?<DesktopServicesMenu key={`${href}:${pathname}`} services={services} active={active}/>:<Link key={href} href={href} aria-current={active?"page":undefined} className={navLinkClass(active)}>{label}</Link>;})}</div>
    <div className="hidden shrink-0 items-center gap-2 lg:flex"><CartLink count={cartCount}/>{!hydrated?<AuthPlaceholder/>:user?<UserMenu name={user.name||user.email||"Kullanıcı"} panel={panel} signOut={signOut}/>:<GuestActions/>}</div>
    <div className="flex items-center gap-2 lg:hidden"><CartLink count={cartCount}/><button type="button" onClick={()=>setOpen(!open)} className="rounded-full border px-3.5 py-2 text-sm" aria-expanded={open} aria-controls="mobile-site-menu">Menü</button></div>
    <div id="mobile-site-menu" className={`${open?"grid":"hidden"} w-full gap-1 border-t pb-5 pt-4 lg:hidden`}>{navigation.map(([label,href])=>label==="Hizmetler"?<MobileServicesMenu key={href} services={services} active={isActivePath(pathname,href)} close={()=>setOpen(false)}/>:<MobileLink key={href} href={href} close={()=>setOpen(false)} active={isActivePath(pathname,href)}>{label}</MobileLink>)}<div className="my-2 border-t"/>{!hydrated?<MobileAuthPlaceholder/>:!user?<><MobileLink href="/login" close={()=>setOpen(false)}>Giriş Yap</MobileLink><Link href="/register" onClick={()=>setOpen(false)} className="mt-1 rounded-full bg-primary px-4 py-2.5 text-center text-sm font-semibold text-primary-foreground">Kayıt Ol</Link></>:<><div className="flex items-center gap-3 px-3 pb-2"><Avatar name={user.name||user.email||"Kullanıcı"}/><span className="text-sm font-semibold">{user.name||user.email||"Kullanıcı"}</span></div><MobileLink href="/profile" close={()=>setOpen(false)}>Profilim</MobileLink><MobileLink href="/appointments" close={()=>setOpen(false)}>Randevularım</MobileLink><MobileLink href="/orders" close={()=>setOpen(false)}>Siparişlerim</MobileLink>{panel?<MobileLink href={panel.href} close={()=>setOpen(false)} accent>{panel.label}</MobileLink>:null}<div className="my-1 border-t"/><button type="button" onClick={signOut} className="rounded-xl px-3 py-2.5 text-left text-sm text-danger hover:bg-muted-surface">Çıkış Yap</button></>}</div>
  </nav></header>;
}

const menuCategories=serviceCategories.filter((category):category is Exclude<ServiceCategory,"Tümü">=>category!=="Tümü");
function groupedServices(services:ServiceItem[]){return menuCategories.map((category)=>({category,items:services.filter((service)=>categoryFor(service)===category)}));}
function navLinkClass(active:boolean){return `relative rounded-full px-2.5 py-2 text-[13px] transition-colors after:absolute after:bottom-0.5 after:left-1/2 after:h-px after:-translate-x-1/2 after:bg-primary after:transition-[width] xl:px-3 xl:text-sm ${active?"font-semibold text-primary after:w-5":"text-muted after:w-0 hover:text-primary"}`;}
function DesktopServicesMenu({services,active}:{services:ServiceItem[];active:boolean}){const[open,setOpen]=useState(false);const rootRef=useRef<HTMLDivElement>(null);useEffect(()=>{function outside(event:PointerEvent){if(!rootRef.current?.contains(event.target as Node))setOpen(false);}function escape(event:KeyboardEvent){if(event.key==="Escape"){setOpen(false);rootRef.current?.querySelector<HTMLAnchorElement>("a")?.focus();}}document.addEventListener("pointerdown",outside);document.addEventListener("keydown",escape);return()=>{document.removeEventListener("pointerdown",outside);document.removeEventListener("keydown",escape);};},[]);function blur(event:React.FocusEvent<HTMLDivElement>){if(!event.currentTarget.contains(event.relatedTarget as Node|null))setOpen(false);}return <div ref={rootRef} className="relative" onMouseEnter={()=>setOpen(true)} onMouseLeave={()=>setOpen(false)} onFocus={()=>setOpen(true)} onBlur={blur}><Link href="/services" onClick={()=>setOpen(false)} aria-current={active?"page":undefined} aria-expanded={open} className={`${navLinkClass(active)} inline-flex items-center gap-1`}><span>Hizmetler</span><span className={`text-[10px] transition-transform duration-200 ${open?"rotate-180":""}`} aria-hidden="true">⌄</span></Link><div className={`${open?"visible translate-y-0 opacity-100":"invisible translate-y-2 opacity-0"} fixed left-6 right-6 top-[140px] mx-auto max-w-[1160px] rounded-[1.5rem] border border-primary/15 bg-[#fffaf4] p-6 shadow-[0_24px_60px_rgba(79,52,43,.14)] transition-all duration-200`}><div className="grid grid-cols-5 gap-6">{groupedServices(services).map(({category,items})=><div key={category} className="min-w-0"><Link href={`/services?category=${serviceCategorySlugs[category]}`} onClick={()=>setOpen(false)} className="inline-flex border-b border-primary/20 pb-2 text-sm font-semibold text-primary hover:border-primary">{category}</Link><div className="mt-3 grid gap-1.5">{items.length?items.map((service)=><Link key={service.id} href={`/services/${service.slug}`} onClick={()=>setOpen(false)} className="group/service flex items-start justify-between gap-2 rounded-lg px-2 py-1.5 text-xs leading-5 text-muted transition-colors hover:bg-[#f3e4dc] hover:text-primary focus-visible:outline-2 focus-visible:outline-primary"><span>{service.name}</span><span className="opacity-0 transition-opacity group-hover/service:opacity-100" aria-hidden="true">→</span></Link>):<span className="px-2 py-1.5 text-xs italic text-muted">Yakında</span>}</div></div>)}</div><div className="mt-5 border-t border-primary/10 pt-4 text-right"><Link href="/services" onClick={()=>setOpen(false)} className="text-sm font-semibold text-primary hover:underline">Tüm hizmetleri görün →</Link></div></div></div>}
function MobileServicesMenu({services,active,close}:{services:ServiceItem[];active:boolean;close:()=>void}){return <details className="group/mobile rounded-xl"><summary className={`flex cursor-pointer list-none items-center justify-between rounded-xl px-3 py-2.5 text-sm transition-colors ${active?"bg-muted-surface font-semibold text-primary":"text-muted hover:bg-muted-surface hover:text-primary"}`}><span>Hizmetler</span><span className="transition-transform duration-200 group-open/mobile:rotate-180" aria-hidden="true">⌄</span></summary><div className="ml-3 border-l border-primary/15 pb-2 pl-3">{groupedServices(services).map(({category,items})=><details key={category} className="group/category"><summary className="flex cursor-pointer list-none items-center justify-between rounded-lg px-3 py-2 text-sm font-medium text-primary hover:bg-muted-surface"><span>{category}</span><span className="transition-transform group-open/category:rotate-90" aria-hidden="true">›</span></summary><div className="grid gap-0.5 pb-2 pl-3">{items.length?items.map((service)=><Link key={service.id} href={`/services/${service.slug}`} onClick={close} className="rounded-lg px-3 py-2 text-sm text-muted hover:bg-muted-surface hover:text-primary">{service.name}</Link>):<Link href={`/services?category=${serviceCategorySlugs[category]}`} onClick={close} className="rounded-lg px-3 py-2 text-xs italic text-muted">Bu kategoriyi görüntüle</Link>}</div></details>)}<Link href="/services" onClick={close} className="mt-1 block rounded-lg px-3 py-2 text-sm font-semibold text-primary">Tüm Hizmetler →</Link></div></details>}

function AuthPlaceholder(){return <div className="h-10 w-36 animate-pulse rounded-full bg-muted-surface" aria-hidden="true"/>}
function MobileAuthPlaceholder(){return <div className="h-24 animate-pulse rounded-xl bg-muted-surface" aria-hidden="true"/>}
function GuestActions(){return <><Link href="/login" className="rounded-full border px-4 py-2 text-sm font-medium hover:border-primary">Giriş Yap</Link><Link href="/register" className="rounded-full bg-primary px-4 py-2 text-sm font-semibold text-primary-foreground hover:bg-[#765246]">Kayıt Ol</Link></>}
function UserMenu({name,panel,signOut}:{name:string;panel:{href:string;label:string}|null;signOut:()=>Promise<void>}){return <details className="relative"><summary className="flex cursor-pointer list-none items-center gap-2 rounded-full py-1.5 pl-1.5 pr-3 hover:bg-muted-surface"><Avatar name={name}/><span className="max-w-32 truncate text-sm font-semibold">{name.split(" ")[0]}</span><span className="text-xs text-muted" aria-hidden="true">▾</span></summary><div className="absolute right-0 mt-2 grid min-w-56 gap-1 rounded-2xl border bg-card p-2 shadow-md"><p className="px-3 py-2 text-xs text-muted">{name}</p><MenuLink href="/profile">Profilim</MenuLink><MenuLink href="/appointments">Randevularım</MenuLink><MenuLink href="/orders">Siparişlerim</MenuLink>{panel?<MenuLink href={panel.href} accent>{panel.label}</MenuLink>:null}<div className="my-1 border-t"/><button type="button" onClick={signOut} className="rounded-xl px-3 py-2 text-left text-sm text-danger hover:bg-muted-surface">Çıkış Yap</button></div></details>}
function Avatar({name}:{name:string}){return <span className="grid size-8 shrink-0 place-items-center rounded-full bg-secondary font-serif text-sm font-semibold text-secondary-foreground">{name.trim().charAt(0).toLocaleUpperCase("tr-TR")||"K"}</span>}
function CartLink({count}:{count:number}){return <Link href="/cart" aria-label="Sepet" className="group relative grid size-11 shrink-0 cursor-pointer place-items-center rounded-full border bg-card text-foreground transition-colors duration-200 hover:border-primary hover:bg-[#f3e4dc] hover:text-primary focus-visible:border-primary focus-visible:bg-[#f3e4dc] focus-visible:text-primary focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary focus-visible:ring-offset-2"><svg width="21" height="21" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d="M6.8 8.5h10.4l1 11H5.8l1-11Z"/><path d="M9 9V6.5a3 3 0 0 1 6 0V9"/></svg>{count>0?<span className="absolute -right-1 -top-1 grid min-h-5 min-w-5 place-items-center rounded-full bg-primary px-1 text-[10px] font-bold leading-none text-primary-foreground ring-2 ring-card">{count>99?"99+":count}</span>:null}</Link>}
function MenuLink({href,accent=false,children}:{href:string;accent?:boolean;children:React.ReactNode}){return <Link href={href} className={`rounded-xl px-3 py-2 text-sm ${accent?"bg-muted-surface font-semibold text-primary":"hover:bg-muted-surface"}`}>{children}</Link>}
function MobileLink({href,close,accent=false,active=false,children}:{href:string;close:()=>void;accent?:boolean;active?:boolean;children:React.ReactNode}){return <Link href={href} onClick={close} aria-current={active?"page":undefined} className={`relative rounded-xl px-3 py-2.5 text-sm transition-colors ${accent||active?"bg-muted-surface font-semibold text-primary":"text-muted hover:bg-muted-surface hover:text-primary"} ${active?"before:absolute before:bottom-2 before:left-3 before:h-px before:w-5 before:bg-primary":""}`}>{children}</Link>}

function isActivePath(pathname:string,href:string){
  if(href==="/")return pathname==="/";
  if(href==="/packages")return pathname==="/packages"||pathname.startsWith("/packages/");
  if(href==="/products")return pathname==="/products"||pathname.startsWith("/products/");
  if(href==="/services")return pathname==="/services"||pathname.startsWith("/services/");
  if(href==="/blog")return pathname==="/blog"||pathname.startsWith("/blog/");
  return pathname===href;
}

function TopContactBar(){return <div className="border-b border-primary/10 bg-[#f8f3ef]"><div className="mx-auto flex min-h-11 max-w-[1440px] items-center justify-between gap-4 px-5 sm:px-8 lg:px-10 xl:px-12"><div className="flex min-w-0 items-center gap-4 text-[11px] text-muted sm:gap-5 lg:gap-7"><span className="hidden items-center gap-1.5 md:flex"><PinIcon/>İstanbul</span><a href="tel:+902120000000" className="flex shrink-0 items-center gap-1.5 transition-colors duration-200 hover:text-primary focus-visible:rounded focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-primary"><PhoneIcon/><span className="sm:hidden">Ara</span><span className="hidden sm:inline">+90 (212) 000 00 00</span></a><a href="mailto:info@lotusguzellik.com" className="hidden items-center gap-1.5 transition-colors duration-200 hover:text-primary focus-visible:rounded focus-visible:outline-2 focus-visible:outline-offset-2 focus-visible:outline-primary md:flex"><MailIcon/>info@lotusguzellik.com</a><span className="flex shrink-0 items-center gap-1.5"><ClockIcon/><span className="sm:hidden">09:00–19:00</span><span className="hidden sm:inline">Pzt - Cmt: 09:00 - 19:00</span></span></div><div className="hidden shrink-0 items-center gap-1.5 md:flex" aria-label="Sosyal medya"><SocialButton label="Instagram"><InstagramIcon/></SocialButton><SocialButton label="Facebook"><FacebookIcon/></SocialButton><SocialButton label="YouTube"><YoutubeIcon/></SocialButton></div></div></div>}

function SocialButton({label,children}:{label:string;children:React.ReactNode}){return <button type="button" aria-label={`${label} yakında`} title={`${label} bağlantısı yakında aktif olacak`} className="grid size-8 cursor-pointer place-items-center rounded-full text-muted transition-colors duration-200 hover:bg-[#f0dfd6] hover:text-primary focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-primary focus-visible:ring-offset-1">{children}</button>}
function Icon({children}:{children:React.ReactNode}){return <svg className="size-3.5 shrink-0 text-primary" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{children}</svg>}
function PinIcon(){return <Icon><path d="M20 10c0 5-8 11-8 11S4 15 4 10a8 8 0 1 1 16 0Z"/><circle cx="12" cy="10" r="2.5"/></Icon>}
function PhoneIcon(){return <Icon><path d="M22 16.9v3a2 2 0 0 1-2.2 2 19.8 19.8 0 0 1-8.6-3.1 19.4 19.4 0 0 1-6-6A19.8 19.8 0 0 1 2.1 4.2 2 2 0 0 1 4.1 2h3a2 2 0 0 1 2 1.7c.1 1 .4 2 .7 2.9a2 2 0 0 1-.4 2.1L8.1 10a16 16 0 0 0 6 6l1.3-1.3a2 2 0 0 1 2.1-.4c1 .4 1.9.6 2.9.7a2 2 0 0 1 1.6 1.9Z"/></Icon>}
function MailIcon(){return <Icon><rect x="3" y="5" width="18" height="14" rx="2"/><path d="m3 7 9 6 9-6"/></Icon>}
function ClockIcon(){return <Icon><circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/></Icon>}
function InstagramIcon(){return <Icon><rect x="3" y="3" width="18" height="18" rx="5"/><circle cx="12" cy="12" r="4"/><path d="M17.5 6.5h.01"/></Icon>}
function FacebookIcon(){return <Icon><path d="M14 8h3V4h-3a5 5 0 0 0-5 5v3H6v4h3v6h4v-6h3l1-4h-4V9a1 1 0 0 1 1-1Z"/></Icon>}
function YoutubeIcon(){return <Icon><path d="M21.6 7.2a2.8 2.8 0 0 0-2-2C17.8 4.7 12 4.7 12 4.7s-5.8 0-7.6.5a2.8 2.8 0 0 0-2 2A29 29 0 0 0 2 12a29 29 0 0 0 .4 4.8 2.8 2.8 0 0 0 2 2c1.8.5 7.6.5 7.6.5s5.8 0 7.6-.5a2.8 2.8 0 0 0 2-2A29 29 0 0 0 22 12a29 29 0 0 0-.4-4.8Z"/><path d="m10 15 5-3-5-3v6Z"/></Icon>}
