"use client";
import { useEffect,useState } from "react";
import { adminService } from "@/services/admin-service";
import { ApiError } from "@/types/api";
import type { DashboardStats } from "@/types/admin";
import type { Order } from "@/types/commerce";
import { commerceMoney } from "@/features/commerce/commerce-format";
import { AdminHeader,AdminPanel,Feedback,LoadingState } from "./admin-ui";
const initial:DashboardStats={customers:0,staff:0,active_services:0,today_appointments:0,pending_appointments:0,orders:0,paid_orders:0,revenue:0};
export function AdminDashboard(){const[stats,setStats]=useState(initial);const[loading,setLoading]=useState(true);const[error,setError]=useState("");useEffect(()=>{let active=true;const today=new Intl.DateTimeFormat("en-CA",{timeZone:"Europe/Istanbul"}).format(new Date());Promise.all([adminService.list("/users",{role:"customer",per_page:1}),adminService.list("/staff",{per_page:1}),adminService.list("/admin/services",{is_active:1,per_page:1}),adminService.appointments({date:today,per_page:1}),adminService.appointments({status:"pending",per_page:1}),adminService.orders({per_page:1}),adminService.orders({payment_status:"paid",per_page:100})]).then((values)=>{if(!active)return;const paid=values[6] as {items:Order[];meta:{total:number}};setStats({customers:values[0].meta.total,staff:values[1].meta.total,active_services:values[2].meta.total,today_appointments:values[3].meta.total,pending_appointments:values[4].meta.total,orders:values[5].meta.total,paid_orders:paid.meta.total,revenue:paid.items.reduce((sum,item)=>sum+Number(item.grand_total),0)});}).catch((reason)=>{if(active)setError(reason instanceof ApiError?reason.message:"Dashboard verileri yüklenemedi.");}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[]);if(loading)return <LoadingState label="Dashboard yükleniyor…"/>;const cards=[["M",'Toplam müşteri',stats.customers,"Kayıtlı müşteriler"],["P",'Toplam personel',stats.staff,"Aktif ekip görünümü"],["H",'Aktif hizmet',stats.active_services,"Yayındaki hizmetler"],["R",'Bugünkü randevu',stats.today_appointments,"Bugünün programı"],["B",'Bekleyen randevu',stats.pending_appointments,"Onay bekleyenler"],["S",'Toplam sipariş',stats.orders,"Tüm siparişler"],["Ö",'Ödenmiş sipariş',stats.paid_orders,"Ödemesi tamamlanan"],["₺",'Ciro (ilk 100 ödenmiş)',commerceMoney(stats.revenue),"Güncel liste özeti"]];return <div className="grid gap-6"><AdminHeader title="Dashboard" description="Operasyonun temel göstergelerine hızlı bakış."/>{error?<Feedback>{error}</Feedback>:null}<div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{cards.map(([icon,label,value,help])=><AdminPanel key={String(label)} className="relative overflow-hidden"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-semibold uppercase tracking-wide text-muted">{label}</p><p className="mt-2 text-2xl font-bold">{value}</p><p className="mt-1 text-xs text-muted">{help}</p></div><span className="grid size-9 place-items-center rounded-xl bg-secondary text-sm font-bold text-secondary-foreground" aria-hidden="true">{icon}</span></div></AdminPanel>)}</div><AdminPanel><p className="text-sm text-muted">Ciro değeri mevcut admin order listeleme sözleşmesindeki ilk 100 ödenmiş sipariş üzerinden gösterilir; finansal raporlama endpointi değildir.</p></AdminPanel></div>}
