import type { Metadata } from "next";
import Link from "next/link";
import { Reveal } from "@/components/ui/reveal";

export const metadata:Metadata={title:"Bakım Paketleri"};
const packages=[
  {name:"Lotus Işıltı",subtitle:"Cilt bakım ritüeli",duration:"120 dakika",price:"3.250 TL",advantage:"Tekli hizmetlere göre avantajlı",items:["Cilt analizi","Yoğun nem bakımı","Yüz masajı"]},
  {name:"Baştan Aşağı Yenilenme",subtitle:"Bütünsel bakım",duration:"180 dakika",price:"4.900 TL",advantage:"En çok tercih edilen paket",items:["Cilt bakımı","Saç bakım ritüeli","El ve ayak bakımı"]},
  {name:"Sakinlik Molası",subtitle:"Kendinize ayırdığınız zaman",duration:"90 dakika",price:"2.750 TL",advantage:"Dingin bir Lotus deneyimi",items:["Aromatik bakım","Rahatlatıcı masaj","Bakım danışmanlığı"]},
];
export default function PackagesPage(){return <><section className="bg-[#f7f2ed] px-4 pb-14 pt-12 sm:px-6 sm:pb-20 sm:pt-16 lg:px-8"><div className="mx-auto overflow-hidden rounded-[2.25rem] border border-[#eadfd8] bg-[#ead6cc] px-7 py-14 text-center shadow-[0_24px_70px_rgba(91,64,53,.07)] sm:px-12 lg:max-w-[1240px] lg:py-20"><p className="text-xs font-bold uppercase tracking-[.28em] text-primary">Lotus bakım paketleri</p><h1 className="mx-auto mt-5 max-w-3xl text-4xl leading-tight sm:text-5xl lg:text-[3.5rem]">Bakımınızı size özel bir ritüele dönüştürün.</h1><p className="mx-auto mt-6 max-w-2xl text-sm leading-7 text-muted sm:text-base">Birbirini tamamlayan hizmetlerden oluşan paketleri keşfedin; uygun zamanınızı mevcut randevu akışında planlayın.</p></div></section><section className="mx-auto max-w-7xl px-4 py-16 sm:px-6 lg:px-8 lg:py-24" aria-labelledby="packages-title"><div className="max-w-2xl"><p className="text-xs font-bold uppercase tracking-[.22em] text-primary">Paket seçkisi</p><h2 id="packages-title" className="mt-3 text-4xl sm:text-5xl">Size iyi gelen zamanı seçin.</h2><p className="mt-4 text-sm leading-7 text-muted">Paketler tanıtım amaçlıdır. Hizmet ve uzman seçimi randevu adımında güncel müsaitliğe göre yapılır.</p></div><div className="mt-12 grid gap-6 lg:grid-cols-3">{packages.map((item,index)=><Reveal key={item.name} delay={index*80}><article className="flex h-full flex-col rounded-[2rem] border border-primary/15 bg-card p-7 shadow-[0_14px_35px_rgba(91,64,53,.05)]"><p className="text-xs font-bold uppercase tracking-[.18em] text-primary">{item.subtitle}</p><h3 className="mt-3 text-3xl">{item.name}</h3><ul className="mt-6 grid gap-3 border-y border-primary/15 py-5 text-sm text-muted">{item.items.map(content=><li key={content} className="flex gap-2"><span className="text-primary" aria-hidden="true">✦</span>{content}</li>)}</ul><dl className="mt-5 grid grid-cols-2 gap-4"><div><dt className="text-xs uppercase tracking-wide text-muted">Toplam süre</dt><dd className="mt-1 font-semibold">{item.duration}</dd></div><div><dt className="text-xs uppercase tracking-wide text-muted">Paket fiyatı</dt><dd className="mt-1 font-serif text-xl text-primary">{item.price}</dd></div></dl><p className="mt-5 rounded-xl bg-muted-surface px-4 py-3 text-sm font-semibold text-primary">{item.advantage}</p><Link href="/appointments/new" className="mt-7 inline-flex items-center justify-center rounded-full bg-primary px-7 py-3.5 text-sm font-semibold text-primary-foreground hover:bg-[#765246] focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-primary">Randevu Al</Link></article></Reveal>)}</div></section></>}
