import Link from "next/link";
import { CampaignShowcase } from "@/features/campaigns/campaign-showcase";

const conditions = [
  ["Kampanyalar ne zaman geçerlidir?", "Kampanyalar kartlarda belirtilen tarihler ve dönemler boyunca geçerlidir."],
  ["Kampanyalar birleştirilebilir mi?", "Bazı fırsatlar başka kampanya veya kuponlarla birleştirilemeyebilir."],
  ["Müsaitlik ve stok koşulu var mı?", "Kampanyalar ürün stoğuna, uzman takvimine ve hizmet müsaitliğine bağlıdır."],
  ["Üyelik gerekli mi?", "Bazı kampanyalar yalnızca Belle Aura hesabı bulunan üyelerimize özel olabilir."],
  ["Koşullar değişebilir mi?", "Belle Aura Beauty, kampanya süresi ve koşullarında gerekli güncellemeleri yapabilir."],
] as const;

export default function CampaignsPage() { return <>
  <section className="bg-[#f7f2ed] px-4 pb-16 pt-16 sm:px-6 sm:pt-20 lg:px-8 lg:pb-24"><div className="mx-auto grid max-w-[1280px] overflow-hidden rounded-[2.25rem] border border-[#eadfd8] bg-card shadow-[0_24px_70px_rgba(91,64,53,.07)] lg:grid-cols-[1.05fr_.95fr]">
    <div className="flex flex-col justify-center px-7 py-14 sm:px-12 lg:px-16 lg:py-20"><p className="text-xs font-bold uppercase tracking-[.28em] text-primary">Kampanyalar</p><h1 className="mt-5 max-w-2xl text-4xl leading-tight sm:text-5xl lg:text-[3.5rem]">Kendinize ayırdığınız zamanı daha özel hale getirin.</h1><p className="mt-6 max-w-xl text-sm leading-7 text-muted sm:text-base">Hizmetlerde ve seçili ürünlerde dönemsel fırsatları keşfedin.</p><div className="mt-8 flex flex-wrap gap-3"><PrimaryLink href="#current-campaigns">Kampanyaları İncele</PrimaryLink><SecondaryLink href="/appointments/new">Randevu Al</SecondaryLink></div></div>
    <div className="relative min-h-[400px] overflow-hidden border-t border-[#eadfd8] bg-[#dfc0b3] lg:min-h-[540px] lg:border-l lg:border-t-0" role="img" aria-label="Kampanyalar için sıcak pastel beauty ve wellness kompozisyonu"><div className="absolute -right-[8%] top-[8%] h-[80%] w-[70%] rounded-[10rem_10rem_2rem_2rem] bg-[#f3e4db]/65"/><div className="absolute bottom-[14%] left-[12%] h-[42%] w-[25%] rounded-[5rem_5rem_1rem_1rem] bg-[#a87463]/50"/><div className="absolute left-[24%] top-[17%] size-28 rounded-full border border-white/70 bg-white/25"/><div className="absolute bottom-[13%] right-[14%] h-48 w-24 rounded-[3rem] bg-[#c99684]/65"/></div>
  </div></section>

  <section className="mx-auto max-w-7xl px-4 py-20 sm:px-6 lg:px-8 lg:py-28" aria-labelledby="featured-title"><p className="text-xs font-bold uppercase tracking-[.22em] text-primary">Öne çıkan kampanya</p><div className="mt-6 grid overflow-hidden rounded-[2.5rem] bg-[#ead6cc] lg:grid-cols-[.9fr_1.1fr]"><div className="relative min-h-80 overflow-hidden bg-[#d3ab9b] lg:min-h-[520px]" role="img" aria-label="Bakım Haftası kampanyası editorial görseli"><div className="absolute left-[13%] top-[14%] h-[74%] w-[57%] rounded-[8rem_8rem_2rem_2rem] bg-white/30"/><div className="absolute bottom-[12%] right-[10%] size-48 rounded-full bg-[#8e6254]/25"/><span className="absolute bottom-8 left-8 font-serif text-sm italic text-primary">the care edit</span></div><div className="flex flex-col justify-center px-7 py-12 sm:px-12 lg:px-16"><span className="w-fit rounded-full bg-primary px-4 py-2 text-xs font-bold uppercase tracking-[.15em] text-primary-foreground">Bakım Haftası</span><h2 id="featured-title" className="mt-6 text-4xl leading-tight sm:text-5xl">Seçili bakım hizmetlerinde %20 avantaj</h2><p className="mt-5 max-w-xl text-sm leading-7 text-muted">Belirli hizmetlerde sınırlı süreli özel fırsat. Randevu ve uzman müsaitliğine göre değerlendirilir.</p><div className="mt-7 grid gap-3 border-y border-primary/15 py-5 text-sm sm:grid-cols-2"><p><strong>Bitiş:</strong> 30 Eylül</p><p><strong>Koşul:</strong> Seçili hizmetlerde geçerli</p></div><div className="mt-8 flex flex-wrap gap-3"><PrimaryLink href="/appointments/new">Randevu Al</PrimaryLink><SecondaryLink href="#conditions">Detayları Gör</SecondaryLink></div></div></div></section>

  <CampaignShowcase />

  <section className="bg-[#f4ede6]"><div className="mx-auto max-w-7xl px-4 py-20 sm:px-6 lg:px-8 lg:py-28"><p className="text-xs font-bold uppercase tracking-[.22em] text-primary">Kolayca keşfedin</p><h2 className="mt-3 text-4xl sm:text-5xl">Kampanyadan Nasıl Yararlanırım?</h2><div className="mt-12 grid gap-8 md:grid-cols-3">{[["01","Kampanyayı seç","Size uygun fırsatı ve geçerlilik koşullarını inceleyin."],["02","Randevunu veya ürününü belirle","Hizmet zamanınızı planlayın ya da ürün seçkinizi oluşturun."],["03","Avantajından yararlan","Geçerli koşullar kapsamında Belle Aura deneyiminizi tamamlayın."]].map(([no,title,text]) => <article key={no} className="border-t border-primary/25 pt-6"><span className="font-serif text-5xl text-primary/55">{no}</span><h3 className="mt-6 text-2xl">{title}</h3><p className="mt-3 max-w-sm text-sm leading-7 text-muted">{text}</p></article>)}</div></div></section>

  <section id="conditions" className="mx-auto grid max-w-7xl scroll-mt-28 gap-12 px-4 py-20 sm:px-6 lg:grid-cols-[.8fr_1.2fr] lg:px-8 lg:py-28" aria-labelledby="conditions-title"><div><p className="text-xs font-bold uppercase tracking-[.22em] text-primary">Bilmeniz gerekenler</p><h2 id="conditions-title" className="mt-3 text-4xl sm:text-5xl">Kampanya Koşulları</h2><p className="mt-5 max-w-sm text-sm leading-7 text-muted">Fırsatlardan yararlanmadan önce kısa koşulları gözden geçirin.</p></div><div className="divide-y border-y">{conditions.map(([question,answer]) => <details key={question} className="group"><summary className="flex cursor-pointer list-none items-center justify-between gap-6 py-6 text-lg font-semibold focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-primary">{question}<span className="text-2xl font-light text-primary transition-transform group-open:rotate-45 motion-reduce:transition-none" aria-hidden="true">+</span></summary><p className="max-w-2xl pb-6 pr-10 text-sm leading-7 text-muted">{answer}</p></details>)}</div></section>

  <section className="mx-auto max-w-7xl px-4 pb-8 sm:px-6 lg:px-8"><div className="rounded-[2.5rem] bg-[#e5c5b7] px-7 py-16 text-center sm:px-12 lg:py-20"><p className="text-xs font-bold uppercase tracking-[.22em] text-primary">Belle Aura fırsatları</p><h2 className="mt-4 text-4xl sm:text-5xl">Fırsatları kaçırmayın.</h2><div className="mt-8 flex flex-wrap justify-center gap-3"><PrimaryLink href="/appointments/new">Randevu Al</PrimaryLink><SecondaryLink href="/products">Ürünleri Keşfet</SecondaryLink></div></div></section>
  </>; }

function PrimaryLink({ href, children }: { href: string; children: React.ReactNode }) { return <Link href={href} className="inline-flex rounded-full bg-primary px-7 py-3.5 text-sm font-semibold text-primary-foreground hover:bg-[#765246] focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-primary">{children}</Link>; }
function SecondaryLink({ href, children }: { href: string; children: React.ReactNode }) { return <Link href={href} className="inline-flex rounded-full border border-primary px-7 py-3.5 text-sm font-semibold text-primary hover:bg-card/40 focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-primary">{children}</Link>; }
