"use client";
/* eslint-disable @next/next/no-img-element */

import Link from "next/link";
import Image from "next/image";
import { useEffect, useState } from "react";
import { appointmentService } from "@/services/appointment-service";
import { mediaUrl } from "@/services/commerce-service";
import type { ServiceItem, StaffItem } from "@/types/appointment";
import { money } from "@/features/appointments/format";
import { categoryFor, SectionHeading, ServiceCard, ServiceVisual } from "./service-ui";
import { demoImages } from "@/lib/demo-images";

export function ServiceDetail({ slug }: { slug: string }) {
  const [service, setService] = useState<ServiceItem | null>(null);
  const [related, setRelated] = useState<ServiceItem[]>([]);
  const [staff, setStaff] = useState<StaffItem[]>([]);
  const [loading, setLoading] = useState(true);
  useEffect(() => { let active = true; appointmentService.services().then(async (page) => { if (!active) return; const found = page.items.find((item) => item.slug === slug); setService(found || null); setRelated(found?page.items.filter((item) => item.slug !== slug&&categoryFor(item)===categoryFor(found)).slice(0,3):[]); if (found) { try { const experts = await appointmentService.staff(found.id); if (active) setStaff(experts.slice(0,4)); } catch {} } }).catch(() => {}).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, [slug]);
  if (loading) return <div className="mx-auto max-w-7xl px-4 py-20 sm:px-6 lg:px-8" aria-label="Hizmet yükleniyor"><div className="h-[560px] animate-pulse rounded-[2.5rem] bg-muted-surface"/></div>;
  if (!service) return <div className="mx-auto max-w-3xl px-4 py-24 text-center"><h1 className="text-5xl">Hizmet bulunamadı</h1><p className="mt-5 text-muted">Aradığınız hizmet artık yayında olmayabilir.</p><Link href="/services" className="mt-8 inline-flex rounded-full bg-primary px-7 py-3.5 text-sm font-semibold text-primary-foreground">Hizmetlere Dön</Link></div>;
  const description = service.description || "Kendinize ayırdığınız zamanı sakin, özenli ve kişisel bir bakım deneyimine dönüştüren profesyonel Lotus hizmetidir.";
  return <>
    <section className="bg-[#f7f2ed] px-4 pb-16 pt-16 sm:px-6 sm:pt-20 lg:px-8 lg:pb-24"><div className="mx-auto grid max-w-[1240px] overflow-hidden rounded-[2.25rem] border border-[#eadfd8] bg-card shadow-[0_24px_70px_rgba(91,64,53,.07)] lg:grid-cols-[1.02fr_.98fr]"><div className="flex flex-col justify-center px-7 py-14 sm:px-12 lg:px-16"><p className="text-xs font-bold uppercase tracking-[.22em] text-primary">{categoryFor(service)}</p><h1 className="mt-5 text-4xl leading-tight sm:text-5xl lg:text-[3.5rem]">{service.name}</h1><p className="mt-6 max-w-xl text-sm leading-7 text-muted">{description}</p><div className="mt-7 flex gap-6 border-y border-primary/15 py-5 text-sm"><span><strong>{service.duration_minutes}</strong> dakika</span><span className="text-primary"><strong>{money(service.price)}</strong></span></div><div className="mt-8 flex flex-wrap gap-3"><PrimaryLink href="/appointments/new">Randevu Al</PrimaryLink><SecondaryLink href="/services">Hizmetlere Dön</SecondaryLink></div></div><div className="min-h-[430px] lg:min-h-[560px]"><ServiceVisual service={service} index={service.id} compact/></div></div></section>

    <section className="mx-auto grid max-w-7xl gap-14 px-4 py-20 sm:px-6 lg:grid-cols-[1fr_.9fr] lg:items-center lg:px-8 lg:py-28" aria-labelledby="what-title"><div><SectionHeading eyebrow="Bakım deneyimi" title={`${service.name} Nedir?`} id="what-title"/><p className="mt-7 max-w-2xl text-base leading-8 text-muted">{description}</p><p className="mt-5 max-w-2xl text-base leading-8 text-muted">Uygulama, kişisel beklentileriniz dinlenerek uzmanınız tarafından planlanır. Amaç kendinizi rahat ve özenli bir bakım sürecinde hissetmenizdir.</p></div><div className="min-h-[430px]"><ServiceVisual service={service} index={service.id + 1} compact/></div></section>

    <section className="bg-[#f4ede6]"><div className="mx-auto max-w-7xl px-4 py-20 sm:px-6 lg:px-8 lg:py-24"><SectionHeading eyebrow="Adım adım" title="Nasıl Uygulanır?" text="Her uygulama hizmetin niteliğine ve kişisel ihtiyaçlarınıza göre uzmanınız tarafından uyarlanır."/><div className="mt-12 grid gap-8 sm:grid-cols-2 lg:grid-cols-4">{[["01","Hazırlık","Beklentileriniz dinlenir ve uygulama alanı hazırlanır."],["02","Uygulama","Hizmet, konforunuz gözetilerek özenle gerçekleştirilir."],["03","Kontrol","Uygulama sonucu ve ihtiyaç duyulan son dokunuşlar değerlendirilir."],["04","Bakım önerileri","Deneyimi evde destekleyecek genel bakım önerileri paylaşılır."]].map(([no,title,text]) => <article key={no} className="border-t border-primary/25 pt-6"><span className="font-serif text-5xl text-primary/55">{no}</span><h3 className="mt-5 text-2xl">{title}</h3><p className="mt-3 text-sm leading-7 text-muted">{text}</p></article>)}</div></div></section>

    <ServiceGallery service={service}/>

    <section className="mx-auto max-w-7xl px-4 py-20 sm:px-6 lg:px-8 lg:py-28"><SectionHeading eyebrow="Tek bakışta" title="İşlem Bilgileri"/><dl className="mt-10 grid overflow-hidden rounded-[2rem] border bg-card sm:grid-cols-2 lg:grid-cols-4">{[["Süre",`${service.duration_minutes} dakika`],["Fiyat",money(service.price)],["Randevu tipi","Uzman eşliğinde"],["Uygulama alanı",categoryFor(service)]].map(([label,value],index) => <div key={label} className={`p-7 ${index ? "border-t sm:border-l sm:border-t-0" : ""} ${index === 2 ? "sm:border-l-0 lg:border-l" : ""}`}><dt className="text-xs font-bold uppercase tracking-[.16em] text-muted">{label}</dt><dd className="mt-3 font-serif text-2xl text-primary">{value}</dd></div>)}</dl></section>

    <section className="bg-card"><div className="mx-auto grid max-w-7xl gap-12 px-4 py-20 sm:px-6 lg:grid-cols-2 lg:px-8 lg:py-28"><div><SectionHeading eyebrow="Kişisel bakım" title="Kimler İçin Uygun?"/><p className="mt-6 text-sm leading-8 text-muted">Bakımına özenli bir zaman ayırmak, profesyonel bir uygulama deneyimi yaşamak ve kişisel bakım rutinini desteklemek isteyen misafirler için planlanabilir. Özel hassasiyetlerinizi randevu öncesinde uzmanınızla paylaşmanız önerilir.</p></div><div className="grid gap-6 sm:grid-cols-2"><Advice title="İşlem Öncesi" items={["Beklentilerinizi ve hassasiyetlerinizi paylaşın.","Uygulamaya rahat bir zaman ayırın.","Özel hazırlık gerekip gerekmediğini sorun."]}/><Advice title="İşlem Sonrası" items={["Uzmanınızın genel bakım önerilerini izleyin.","Uygulama alanına nazik davranın.","Sorularınız için Lotus ekibiyle iletişim kurun."]}/></div></div></section>

    <Experts staff={staff}/>
    <Faq duration={service.duration_minutes}/>

    {related.length ? <section className="bg-[#f4ede6]"><div className="mx-auto max-w-7xl px-4 py-20 sm:px-6 lg:px-8 lg:py-28"><SectionHeading eyebrow="Keşfetmeye devam edin" title="Benzer Hizmetler"/><div className="mt-12 grid gap-x-8 gap-y-14 md:grid-cols-3">{related.map((item,index) => <ServiceCard key={item.id} service={item} index={index}/>)}</div></div></section> : null}
    <section className="mx-auto max-w-7xl px-4 py-20 sm:px-6 lg:px-8"><div className="rounded-[2.5rem] bg-[#e5c5b7] px-7 py-16 text-center sm:px-12 lg:py-20"><p className="text-xs font-bold uppercase tracking-[.22em] text-primary">Sizin zamanınız</p><h2 className="mx-auto mt-4 max-w-3xl text-4xl sm:text-5xl">Bakımınız için size uygun zamanı seçin.</h2><div className="mt-8 flex flex-wrap justify-center gap-3"><PrimaryLink href="/appointments/new">Randevu Al</PrimaryLink><SecondaryLink href="/services">Hizmetleri İncele</SecondaryLink></div></div></section>
  </>;
}

function ServiceGallery({service}:{service:ServiceItem}){const category=categoryFor(service);const images=category==="Saç Bakımı"?[demoImages.hair,demoImages.spa,demoImages.products,demoImages.skincare]:category==="Cilt Bakımı"?[demoImages.skincare,demoImages.products,demoImages.spa,demoImages.hair]:[demoImages.spa,demoImages.products,demoImages.skincare,demoImages.hair];return <section className="mx-auto max-w-7xl px-4 py-20 sm:px-6 lg:px-8"><SectionHeading eyebrow="Lotus deneyimi" title="Uygulamadan Kareler" text="Hizmet ortamını ve bakım yaklaşımını temsil eden demo görseller; kişisel sonuç vaadi içermez."/><div className="mt-10 grid grid-cols-2 gap-4 lg:grid-cols-4">{images.map((src,index)=><div key={src} className={`relative overflow-hidden rounded-[1.5rem] ${index%2?"aspect-[4/5]":"aspect-square"}`}><Image src={src} alt={`${service.name} bakım deneyimini temsil eden salon görseli ${index+1}`} fill sizes="(max-width: 768px) 50vw, 25vw" className="object-cover transition-transform duration-300 hover:scale-[1.03] motion-reduce:transition-none"/></div>)}</div></section>}

function Experts({ staff }: { staff: StaffItem[] }) { return <section className="mx-auto max-w-7xl px-4 py-20 sm:px-6 lg:px-8 lg:py-28"><SectionHeading eyebrow="Lotus ekibi" title="Hizmeti Veren Uzmanlar" text="Bu hizmet için randevu oluşturabileceğiniz mevcut uzmanlar."/>{staff.length ? <div className="mt-12 grid gap-8 sm:grid-cols-2 lg:grid-cols-4">{staff.map((expert,index) => { const avatar = mediaUrl(expert.avatar_path); return <article key={expert.id}><div className={`grid aspect-[4/5] place-items-center overflow-hidden rounded-[7rem_7rem_1.5rem_1.5rem] ${["bg-[#e5c4bd]","bg-[#ddd6c9]","bg-[#ead2c5]","bg-[#d8c9c1]"][index]}`}>{avatar ? <img src={avatar} alt={`${expert.name} portresi`} className="size-full object-cover"/> : <span className="font-serif text-5xl text-primary/55" aria-hidden="true">{expert.name.charAt(0)}</span>}</div><p className="mt-5 text-xs font-bold uppercase tracking-[.16em] text-primary">{expert.service_name}</p><h3 className="mt-2 text-2xl">{expert.name}</h3><Link href="/appointments/new" className="mt-5 inline-flex border-b border-primary pb-1 text-sm font-semibold">Randevu Al →</Link></article>; })}</div> : <p className="mt-10 rounded-2xl border bg-card p-6 text-sm text-muted">Uzman bilgileri şu anda görüntülenemiyor. Randevu adımında güncel uzmanları seçebilirsiniz.</p>}</section>; }
function Advice({ title, items }: { title: string; items: string[] }) { return <article className="rounded-[2rem] bg-[#f2e8e1] p-7"><h3 className="text-2xl">{title}</h3><ul className="mt-5 space-y-3 text-sm leading-6 text-muted">{items.map((item) => <li key={item} className="flex gap-3"><span className="text-primary" aria-hidden="true">✦</span>{item}</li>)}</ul></article>; }
function Faq({ duration }: { duration: number }) { const items = [["İşlem ne kadar sürer?",`Bu hizmet için planlanan süre yaklaşık ${duration} dakikadır.`],["Ne sıklıkla yaptırılabilir?","Uygun sıklık kişisel bakım ihtiyacınıza göre değişebilir; uzmanınızla birlikte planlayabilirsiniz."],["Randevu öncesi nelere dikkat etmeliyim?","Hassasiyetlerinizi ve beklentilerinizi uzmanınızla paylaşmanız yeterlidir."],["İşlem sonrası nelere dikkat etmeliyim?","Uzmanınızın paylaştığı genel bakım önerilerini takip edebilirsiniz."],["Randevumu değiştirebilir miyim?","Uygun koşullardaki randevunuzu hesabınızdaki Randevularım alanından yönetebilirsiniz."]] as const; return <section className="mx-auto grid max-w-7xl gap-12 px-4 py-20 sm:px-6 lg:grid-cols-[.8fr_1.2fr] lg:px-8 lg:py-28"><SectionHeading eyebrow="Merak ettikleriniz" title="Sık Sorulan Sorular"/><div className="divide-y border-y">{items.map(([question,answer]) => <details key={question} className="group"><summary className="flex cursor-pointer list-none justify-between gap-5 py-6 text-lg font-semibold focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-primary">{question}<span className="text-2xl text-primary transition-transform group-open:rotate-45 motion-reduce:transition-none" aria-hidden="true">+</span></summary><p className="pb-6 pr-10 text-sm leading-7 text-muted">{answer}</p></details>)}</div></section>; }
function PrimaryLink({ href, children }: { href: string; children: React.ReactNode }) { return <Link href={href} className="inline-flex rounded-full bg-primary px-7 py-3.5 text-sm font-semibold text-primary-foreground focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-primary">{children}</Link>; }
function SecondaryLink({ href, children }: { href: string; children: React.ReactNode }) { return <Link href={href} className="inline-flex rounded-full border border-primary px-7 py-3.5 text-sm font-semibold text-primary focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-primary">{children}</Link>; }
