"use client";
import Link from "next/link";
import { useEffect,useState } from "react";
import { staffService } from "@/services/staff-service";
import { ApiError } from "@/types/api";
import { Feedback,LoadingState } from "@/features/appointments/feedback";
import { StaffHeader,StaffPanel } from "./staff-ui";
interface Stats{today:number;upcoming:number;completed:number}
export function StaffDashboard(){const[stats,setStats]=useState<Stats>({today:0,upcoming:0,completed:0});const[loading,setLoading]=useState(true);const[error,setError]=useState("");useEffect(()=>{let active=true;const today=new Intl.DateTimeFormat("en-CA",{timeZone:"Europe/Istanbul"}).format(new Date());Promise.all([staffService.appointments({date:today,per_page:1}),staffService.appointments({date_from:today,per_page:1}),staffService.appointments({status:"completed",per_page:1})]).then(([current,upcoming,completed])=>{if(active)setStats({today:current.meta.total,upcoming:upcoming.meta.total,completed:completed.meta.total});}).catch((reason)=>{if(active)setError(reason instanceof ApiError?reason.message:"Dashboard yüklenemedi.");}).finally(()=>{if(active)setLoading(false);});return()=>{active=false;};},[]);if(loading)return <LoadingState label="Programınız yükleniyor…"/>;return <div className="grid gap-6"><StaffHeader title="Dashboard" description="Bugünkü programınızı ve randevu özetinizi takip edin."/>{error?<Feedback>{error}</Feedback>:null}<div className="grid gap-4 sm:grid-cols-3"><Stat label="Bugünkü randevular" value={stats.today}/><Stat label="Yaklaşan randevular" value={stats.upcoming}/><Stat label="Tamamlanan randevular" value={stats.completed}/></div><StaffPanel><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><h2 className="font-bold">Bugünün toplam programı</h2><p className="mt-1 text-sm text-muted">Bugün size atanmış {stats.today} randevu bulunuyor.</p></div><Link href="/staff/appointments" className="rounded-xl bg-primary px-5 py-3 text-center text-sm font-semibold text-primary-foreground">Randevularımı aç</Link></div></StaffPanel></div>}
function Stat({label,value}:{label:string;value:number}){return <StaffPanel><p className="text-sm text-muted">{label}</p><p className="mt-3 text-3xl font-bold">{value}</p></StaffPanel>}
